// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v1beta1/gocacheprog.proto

package gocacheprogv1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdType is the definition of the command type.
type CmdType int32

const (
	// CMD_TYPE_UNSPECIFIED is the cmd type is unknown.
	CmdType_CMD_TYPE_UNSPECIFIED CmdType = 0
	// CMD_TYPE_GET is the cmd requires get operation.
	CmdType_CMD_TYPE_GET CmdType = 1
	// CMD_TYPE_PUT is the cmd requires put operation.
	CmdType_CMD_TYPE_PUT CmdType = 2
	// CMD_TYPE_CLOSE is the cmd requires close operation.
	CmdType_CMD_TYPE_CLOSE CmdType = 3
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "CMD_TYPE_UNSPECIFIED",
		1: "CMD_TYPE_GET",
		2: "CMD_TYPE_PUT",
		3: "CMD_TYPE_CLOSE",
	}
	CmdType_value = map[string]int32{
		"CMD_TYPE_UNSPECIFIED": 0,
		"CMD_TYPE_GET":         1,
		"CMD_TYPE_PUT":         2,
		"CMD_TYPE_CLOSE":       3,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1beta1_gocacheprog_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_v1beta1_gocacheprog_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_v1beta1_gocacheprog_proto_rawDescGZIP(), []int{0}
}

// Request is the JSON-encoded message that's sent from cmd/go to
// the GOCACHEPROG child process over stdin. Each JSON object is on its
// own line. A Request of Type "put" with body_size > 0 will be followed
// by a line containing a base64-encoded JSON string literal of the body.
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is a unique number per process across all requests.
	// It must be echoed in the Response from the child.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// command is the type of request.
	// The cmd/go tool will only send commands that were declared
	// as supported by the child.
	Command CmdType `protobuf:"varint,2,opt,name=command,proto3,enum=apis.gocacheprog.v1beta1.CmdType" json:"command,omitempty"`
	// action_id is non-nil for get and puts.
	ActionId []byte `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// output_id is set for Type "put" and "output-file".
	OutputId []byte `protobuf:"bytes,4,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	// body is the body for "put" requests. It's sent after the JSON object
	// as a base64-encoded JSON string when body_size is non-zero.
	// It's sent as a separate JSON value instead of being a struct field
	// send in this JSON object so large values can be streamed in both directions.
	// The base64 string body of a Request will always be written
	// immediately after the JSON object and a newline.
	Body []byte `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// body_size is the number of bytes of body. If zero, the body isn't written.
	BodySize int64 `protobuf:"varint,7,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1beta1_gocacheprog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_v1beta1_gocacheprog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_v1beta1_gocacheprog_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetCommand() CmdType {
	if x != nil {
		return x.Command
	}
	return CmdType_CMD_TYPE_UNSPECIFIED
}

func (x *Request) GetActionId() []byte {
	if x != nil {
		return x.ActionId
	}
	return nil
}

func (x *Request) GetOutputId() []byte {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetBodySize() int64 {
	if x != nil {
		return x.BodySize
	}
	return 0
}

// Response is the JSON response from the child process to cmd/go.
//
// With the exception of the first protocol message that the child writes to its
// stdout with id==0 and knownCommands populated, these are only sent in
// response to a Request from cmd/go.
//
// Responses can be sent in any order. The id must match the request they're
// replying to.
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is a unique number per process across all requests.
	// It must be echoed in the Response from the child.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// error is the error message if the command failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// known_commands is included in the first message that cache helper program
	// writes to stdout on startup (with ID==0). It includes the
	// Request.command types that are supported by the program.
	//
	// This lets us extend the gracefully over time (adding "get2", etc), or
	// fail gracefully when needed. It also lets us verify the program
	// wants to be a cache helper.
	KnowCommands []CmdType `protobuf:"varint,3,rep,packed,name=know_commands,json=knowCommands,proto3,enum=apis.gocacheprog.v1beta1.CmdType" json:"know_commands,omitempty"`
	// miss indicates that the request was a get and the object was not found.
	Miss bool `protobuf:"varint,4,opt,name=miss,proto3" json:"miss,omitempty"`
	// output_id is set for Type "put" and "output-file".
	OutputId []byte `protobuf:"bytes,5,opt,name=output_id,json=outputId,proto3" json:"output_id,omitempty"`
	// size is the size of the body in bytes.
	Size int64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	// time_nanos is the time the entry was created.
	TimeNanos *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=time_nanos,json=timeNanos,proto3" json:"time_nanos,omitempty"`
	// disk_path is the absolute path on disk of the output_id corresponding
	// a "get" request's action_id (on cache hit) or a "put" request's
	// provided output_id.
	DiskPath string `protobuf:"bytes,8,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1beta1_gocacheprog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_v1beta1_gocacheprog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_v1beta1_gocacheprog_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetKnowCommands() []CmdType {
	if x != nil {
		return x.KnowCommands
	}
	return nil
}

func (x *Response) GetMiss() bool {
	if x != nil {
		return x.Miss
	}
	return false
}

func (x *Response) GetOutputId() []byte {
	if x != nil {
		return x.OutputId
	}
	return nil
}

func (x *Response) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Response) GetTimeNanos() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeNanos
	}
	return nil
}

func (x *Response) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

var File_v1beta1_gocacheprog_proto protoreflect.FileDescriptor

var file_v1beta1_gocacheprog_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x67, 0x6f, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x70, 0x72, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x70, 0x69,
	0x73, 0x2e, 0x67, 0x6f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x72, 0x6f, 0x67, 0x2e, 0x76, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x3b, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x67, 0x6f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x70, 0x72, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e, 0x43,
	0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x08, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x95, 0x02, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x46, 0x0a,
	0x0d, 0x6b, 0x6e, 0x6f, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x73, 0x2e, 0x67, 0x6f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x70, 0x72, 0x6f, 0x67, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2e,
	0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6b, 0x6e, 0x6f, 0x77, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x73, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x6d, 0x69, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x50, 0x61,
	0x74, 0x68, 0x2a, 0x5b, 0x0a, 0x07, 0x43, 0x6d, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x14, 0x43, 0x4d, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4d, 0x44, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4d, 0x44,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x55, 0x54, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43,
	0x4d, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x03, 0x42,
	0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69,
	0x76, 0x63, 0x68, 0x61, 0x72, 0x69, 0x2f, 0x67, 0x6f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70, 0x72,
	0x6f, 0x67, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x67, 0x6f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x70,
	0x72, 0x6f, 0x67, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v1beta1_gocacheprog_proto_rawDescOnce sync.Once
	file_v1beta1_gocacheprog_proto_rawDescData = file_v1beta1_gocacheprog_proto_rawDesc
)

func file_v1beta1_gocacheprog_proto_rawDescGZIP() []byte {
	file_v1beta1_gocacheprog_proto_rawDescOnce.Do(func() {
		file_v1beta1_gocacheprog_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1beta1_gocacheprog_proto_rawDescData)
	})
	return file_v1beta1_gocacheprog_proto_rawDescData
}

var file_v1beta1_gocacheprog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1beta1_gocacheprog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1beta1_gocacheprog_proto_goTypes = []interface{}{
	(CmdType)(0),                  // 0: apis.gocacheprog.v1beta1.CmdType
	(*Request)(nil),               // 1: apis.gocacheprog.v1beta1.Request
	(*Response)(nil),              // 2: apis.gocacheprog.v1beta1.Response
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_v1beta1_gocacheprog_proto_depIdxs = []int32{
	0, // 0: apis.gocacheprog.v1beta1.Request.command:type_name -> apis.gocacheprog.v1beta1.CmdType
	0, // 1: apis.gocacheprog.v1beta1.Response.know_commands:type_name -> apis.gocacheprog.v1beta1.CmdType
	3, // 2: apis.gocacheprog.v1beta1.Response.time_nanos:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1beta1_gocacheprog_proto_init() }
func file_v1beta1_gocacheprog_proto_init() {
	if File_v1beta1_gocacheprog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1beta1_gocacheprog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1beta1_gocacheprog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1beta1_gocacheprog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1beta1_gocacheprog_proto_goTypes,
		DependencyIndexes: file_v1beta1_gocacheprog_proto_depIdxs,
		EnumInfos:         file_v1beta1_gocacheprog_proto_enumTypes,
		MessageInfos:      file_v1beta1_gocacheprog_proto_msgTypes,
	}.Build()
	File_v1beta1_gocacheprog_proto = out.File
	file_v1beta1_gocacheprog_proto_rawDesc = nil
	file_v1beta1_gocacheprog_proto_goTypes = nil
	file_v1beta1_gocacheprog_proto_depIdxs = nil
}
